### ISSUE TITLE
End Time in data-input page won't be recorded after going back to it from scoreboard.php with go back button

### ISSUE THREAD

**Issue by lydia7635** [oToToT/JudgeGirl-Scoreboard#5]
As title.
It's convenient that Contest ID will be recorded in this condition.
Therefore, I think it would be better if End Time can also be recorded, instead of data "15xx year" is filled in the blank. (⊙_⊙)

I would appreciate it if the feature is added.
Thanks! <(_ _)>

**Comment by oToToT** [comment]
I think this has been solved in 7c61903, and now it has been deployed, please have a check

**Comment by lydia7635** [comment]
Thanks! It really works!
<(_ _)>
